import { Application } from '@hotwired/stimulus'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { loadDataTableLibrary } from '../src/functions/loadDataTableLibrary.js'

vi.mock('../src/functions/loadDataTableLibrary.js', () => ({
    loadDataTableLibrary: vi.fn(),
}))

vi.mock('../src/functions/detectStyleFramework.js', () => ({
    detectStyleFramework: () => 'dt',
}))

vi.mock('../src/functions/filterFeature.js', () => ({
    registerFilterFeature: vi.fn(),
}))

import DatatableController from '../src/controller.js'

// A browser history restore can hand back the markup DataTables generated on the previous
// document while no live instance exists any more. `render_datatable()` emits an empty
// `<table>`, so anything inside it is stale and must be dropped before re-initializing.
describe('datatable controller history restore', () => {
    let application: Application
    let seen: Array<{ element: Element; childElementCount: number; hadDtClass: boolean }>

    beforeEach(() => {
        seen = []
        const initialized = new WeakSet<Element>()

        function MockDataTable(this: void, element: Element, _payload: unknown) {
            seen.push({
                element,
                childElementCount: element.childElementCount,
                hadDtClass: element.classList.contains('dataTable'),
            })
            initialized.add(element)

            const container = document.createElement('div')
            container.className = 'dt-container'
            container.id = `${element.id}_wrapper`
            element.parentNode?.insertBefore(container, element)
            container.appendChild(element)
            element.classList.add('dataTable')

            return { destroy: vi.fn(), on: vi.fn() }
        }

        MockDataTable.isDataTable = (element: Element) => initialized.has(element)
        MockDataTable.Api = class {
            constructor(_element: Element) {
                return { destroy: vi.fn(), on: vi.fn() }
            }
        }

        vi.mocked(loadDataTableLibrary).mockResolvedValue(MockDataTable)

        application = Application.start()
        application.register('datatable', DatatableController)
    })

    afterEach(() => {
        application.stop()
        document.body.innerHTML = ''
        vi.clearAllMocks()
    })

    it('initializes over a bare table untouched', async () => {
        mountTable()
        await settle()

        expect(seen).toHaveLength(1)
        expect(seen[0].childElementCount).toBe(0)
    })

    it('drops generated markup restored without a live instance', async () => {
        const table = mountRestoredTable()
        await settle()

        expect(seen).toHaveLength(1)
        // The stale header cells are what DataTables would otherwise adopt, producing a column
        // count that no longer matches the payload.
        expect(seen[0].childElementCount).toBe(0)
        expect(seen[0].hadDtClass).toBe(false)
        expect(table.querySelector('#stale-row')).toBeNull()
    })

    it('does not reparent the table when a stale wrapper survives', async () => {
        const wrapper = document.createElement('div')
        wrapper.className = 'dt-container'
        wrapper.id = 'people_wrapper'
        document.body.appendChild(wrapper)

        const staleControl = document.createElement('div')
        staleControl.className = 'dt-search'
        staleControl.id = 'stale-search'
        wrapper.appendChild(staleControl)

        const table = mountRestoredTable(wrapper)
        await settle()

        expect(seen).toHaveLength(1)
        expect(seen[0].childElementCount).toBe(0)
        // Reparenting would make Stimulus reconnect and race a second initialization.
        expect(document.querySelector('#stale-search')).toBeNull()
        expect(table.closest('.dt-container')).not.toBeNull()
    })

    it('leaves an application container that only shares the dt-container class alone', async () => {
        const container = document.createElement('div')
        // Not generated by DataTables: no `<table id>_wrapper` id, and the siblings below belong
        // to the application, not to a torn-down table.
        container.className = 'dt-container'
        document.body.appendChild(container)

        const control = document.createElement('div')
        control.id = 'app-control'
        container.appendChild(control)

        const table = mountRestoredTable(container)

        const sidebar = document.createElement('aside')
        sidebar.id = 'app-sidebar'
        container.appendChild(sidebar)

        await settle()

        expect(seen).toHaveLength(1)
        // The table itself is still emptied - that part is always safe.
        expect(seen[0].childElementCount).toBe(0)
        expect(table.querySelector('#stale-row')).toBeNull()
        expect(document.querySelector('#app-control')).not.toBeNull()
        expect(document.querySelector('#app-sidebar')).not.toBeNull()
    })

    // The wrapper id is a naming convention, not proof of ownership: an application container is
    // free to use it. Removal therefore needs evidence on the node being removed.
    it('keeps unrecognized siblings even inside a container named like the wrapper', async () => {
        const container = document.createElement('div')
        container.className = 'dt-container'
        container.id = 'people_wrapper'
        document.body.appendChild(container)

        const control = document.createElement('div')
        control.id = 'app-control'
        control.innerHTML = '<button type="button">Export</button>'
        container.appendChild(control)

        const staleRow = document.createElement('div')
        staleRow.id = 'stale-row-wrapper'
        // Bootstrap 5 shape: the layout row's own class carries no dt- marker, but the cell inside
        // it does, which is what identifies the subtree as generated.
        staleRow.className = 'row mt-2 justify-content-between'
        staleRow.innerHTML = '<div class="dt-layout-start col-md-auto"><div class="dt-search"></div></div>'
        container.appendChild(staleRow)

        const table = mountRestoredTable(container)
        await settle()

        expect(seen).toHaveLength(1)
        expect(seen[0].childElementCount).toBe(0)
        expect(document.querySelector('#stale-row-wrapper')).toBeNull()
        expect(document.querySelector('#app-control')).not.toBeNull()
        expect(table.closest('.dt-container')).not.toBeNull()
    })

    it('removes a stale control identified only by its table-namespaced id', async () => {
        const wrapper = document.createElement('div')
        wrapper.className = 'dt-container'
        wrapper.id = 'people_wrapper'
        document.body.appendChild(wrapper)

        const info = document.createElement('div')
        info.id = 'people_info'
        wrapper.appendChild(info)

        mountRestoredTable(wrapper)
        await settle()

        expect(document.querySelector('#people_info')).toBeNull()
    })
})

function viewValue(): string {
    return JSON.stringify({
        columns: [
            { data: 'name', title: 'Name' },
            { data: 'email', title: 'Email' },
        ],
    })
}

function mountTable(parent: Element = document.body): HTMLTableElement {
    const table = document.createElement('table')
    table.id = 'people'
    table.setAttribute('data-controller', 'datatable')
    table.setAttribute('data-datatable-view-value', viewValue())
    parent.appendChild(table)
    return table
}

function mountRestoredTable(parent: Element = document.body): HTMLTableElement {
    const table = document.createElement('table')
    table.id = 'people'
    table.setAttribute('data-datatable-view-value', viewValue())
    table.className = 'table dataTable'
    table.innerHTML =
        '<thead><tr><th class="dt-orderable-asc">Name</th><th>Email</th></tr></thead>' +
        '<tbody><tr id="stale-row"><td>Ada</td><td>ada@example.com</td></tr></tbody>'
    parent.appendChild(table)
    // Set last so Stimulus connects to markup that is already in the restored state.
    table.setAttribute('data-controller', 'datatable')
    return table
}

async function settle(): Promise<void> {
    for (let i = 0; i < 20; i++) {
        await new Promise((resolve) => setTimeout(resolve, 0))
    }
}
